// Auto-generated by deploy-opencode from Claude Code hooks.json files.
// Do not edit manually — re-run the converter to update.

export const HooksPlugin = async ({ $ }) => {
  return {
    event: async ({ event }) => {
      // From plugin: obsidian (Claude event: Stop)
      if (event.type === "session.idle") {
        await $`echo '[Knowledge Management] Consider logging significant decisions to your daily note with: obsidian-cli append @daily'`
      }
    },
  }
}
