"""Convert Claude Code hooks.json to OpenCode TypeScript plugin."""

from __future__ import annotations

from deploy_opencode.models import ClaudeHooks

# Mapping from Claude Code hook event names to OpenCode plugin events
HOOK_EVENT_MAP: dict[str, str] = {
    "Stop": "session.idle",
    "PreToolUse": "tool.execute.before",
    "PostToolUse": "tool.execute.after",
}


def convert_hooks(hooks_by_plugin: dict[str, ClaudeHooks]) -> str:
    """Generate an OpenCode TypeScript plugin from Claude Code hooks.

    Args:
        hooks_by_plugin: Mapping of plugin name → ClaudeHooks.

    Returns:
        TypeScript source code for the plugin, or empty string if no hooks.
    """
    if not hooks_by_plugin:
        return ""

    event_handlers: list[str] = []

    for plugin_name, claude_hooks in hooks_by_plugin.items():
        for event_name, hook_groups in claude_hooks.hooks.items():
            oc_event = HOOK_EVENT_MAP.get(event_name)
            if oc_event is None:
                event_handlers.append(
                    f"      // Unmapped Claude hook event: {event_name}"
                )
                continue

            for group in hook_groups:
                for entry in group.hooks:
                    if entry.type == "command":
                        escaped = entry.command.replace("`", "\\`")
                        event_handlers.append(
                            f"      // From plugin: {plugin_name} (Claude event: {event_name})\n"
                            f'      if (event.type === "{oc_event}") {{\n'
                            f"        await $`{escaped}`\n"
                            f"      }}"
                        )

    if not event_handlers:
        return ""

    handlers_block = "\n".join(event_handlers)

    return f"""\
// Auto-generated by deploy-opencode from Claude Code hooks.json files.
// Do not edit manually — re-run the converter to update.

export const HooksPlugin = async ({{ $ }}) => {{
  return {{
    event: async ({{ event }}) => {{
{handlers_block}
    }},
  }}
}}
"""
